version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: udf
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: udf
      DB_PORT: 3306
    depends_on:
      - db
